language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.1
    - android-26

script:
   - ./gradlew build connectedCheck

before_script:
  # Create and start emulator
  - android list targets
  - echo no | android create avd --force -n test -t "android-26" --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &